name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - run: npm ci
    
    - run: npm run build --if-present
    
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }} 
        SOURCE: "dist/"
        ARGS: "--delete"

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: 'ci'
        SLACK_USERNAME: 'CI'
        SLACK_ICON: 'https://www.igoal.com.br/assets/images/favicon.webp'
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: "Projeto: ${{ github.event.repository.name }}"
        SLACK_FOOTER: 'Apertem os cintos :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        MSG_MINIMAL: ref,commit
